name: Unzip and Build Omkar Apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'

      - name: Unzip customer app
        run: unzip customer_app.zip -d customer_app

      - name: Unzip admin app
        run: unzip admin_app.zip -d admin_app

      - name: Build Customer App APK
        run: |
          cd customer_app
          flutter pub get
          flutter build apk --release

      - name: Upload Customer APK
        uses: actions/upload-artifact@v4
        with:
          name: OmkarCustomerAPK
          path: customer_app/build/app/outputs/flutter-apk/app-release.apk

      - name: Build Admin App APK
        run: |
          cd admin_app
          flutter pub get
          flutter build apk --release

      - name: Upload Admin APK
        uses: actions/upload-artifact@v4
        with:
          name: OmkarAdminAPK
          path: admin_app/build/app/outputs/flutter-apk/app-release.apk

